# Site settings

encoding: utf-8

title: Manel Brull
description: > 
  This webpage contains my professional information so everyone can check 
  online. It contains a page for my resume, another one for my projects 
  and a last one which provides additional information if you want to 
  contact me.
baseurl: ""
#url: "https://manelbrull.github.io/" 
url: "http://localhost:4000/"

#Personal details
email: mbrull88@gmail.com
phone: (0034) 663407144

#Professional identity 
twitter_username: ManelBrull
github_username:  ManelBrull
linkedin: https://es.linkedin.com/in/manelbrull



# Build settings
markdown: kramdown
highlighter: rouge
