# Site settings

encoding: utf-8

title: Manel Brull
description: > # this means to ignore newlines until "baseurl:"
  This webpage contains my professional information so everyone can check 
  online. It contains a page for my resume, another one for my projects 
  and a last one which provides additional information if you want to 
  contact me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site

#Personal details
email: mbrull88@gmail.com
phone: (0034) 663407144

#Professional identity 
twitter_username: ManelBrull
github_username:  ManelBrull
linkedin: https://es.linkedin.com/in/manelbrull



# Build settings
markdown: kramdown
highlighter: rouge
